### ISSUE TITLE
Documentation page does not exist

### ISSUE THREAD

**Issue by Frontrider** [Citi/gradle-helm-plugin#13]
When I click the user manual link on the bottom of the readme, It leads to a page that does not exist.
https://citi.github.io/projects/gradle-helm-plugin/

**Comment by imanushin** [comment]
Hi @Frontrider , thank you you very much.

Yes, you are right. I'm working on fixing that.

**Comment by JamieSlome** [comment]
What is the status of this issue? Do we have any updates?

**Comment by magner669** [comment]
I think the latest is that we have a beanch

**Comment by JamieSlome** [comment]
@imanushin @magner669 - can this be closed?

**Comment by Frontrider** [comment]
I'd say that when the link in the first comment (or the one in the readme) does not lead to a 404 page then it can be.

**Comment by imanushin** [comment]
@Frontrider, thank you. The documentation was published here: https://citi.github.io/gradle-helm-plugin/ . Gradle Plugin Portal still has an old link, therefore I prefer to keep issue to be open for some time.

**Comment by Frontrider** [comment]
I consider it fixed, keep this open for as long as it is needed. :+1:

**Comment by imanushin** [comment]
Good point, thank you. Closing the issue.
