### ISSUE TITLE
OverlappingFileLockException during multi project build

### ISSUE THREAD

**Issue by magner669** [Citi/gradle-helm-plugin#14]
When we run a multi project buiid the task helmUpdateRepositories is executed in parallel.

This is flaky especially when the repository index is large, because the index file is shared between all projects.

One possible solution is to avoid using  the shared directory, use a project local directory.

**Comment by kngk1** [comment]
Fixed via #19

**Comment by imanushin** [comment]
@kngk1, thank you.
