### ISSUE TITLE
Introduce the Dependency Review GitHub Action to CI ✅ 

### ISSUE THREAD

**Issue by JamieSlome** [Citi/gradle-helm-plugin#33]
The Dependency Review GitHub Action is very powerful for scanning pull requests for dependency changes and is capable of raising a CI error if vulnerabilities or invalid licenses are being introduced.

I'd recommend using the [following workflow setup](https://github.com/finos/git-proxy/blob/main/.github/workflows/dependency-review.yml):

```bash
name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
     - name: 'Checkout Repository'
       uses: actions/checkout@v4
     - name: Dependency Review
       uses: actions/dependency-review-action@v4
       with:
        comment-summary-in-pr: always
        fail-on-severity: high
        allow-licenses: MIT
        fail-on-scopes: development, runtime
```

**Comment by magner669** [comment]
@[](url)

**Comment by JamieSlome** [comment]
@joeyyy09 - thanks for taking this on! Can you drop a comment below and we should be able to assign this ticket to you! Great work ❤️ 🤗

**Comment by joeyyy09** [comment]
Yeah sure!
