### ISSUE TITLE
Dependency review workflow can't write to pull requests

### ISSUE THREAD

**Issue by magner669** [Citi/gradle-helm-plugin#40]
There is a warning that review-dependencies workflow can't write to the pull request.

I suppose it means ilee can't see whatever advice it provides.

This could block from merging pull requests.

![Screenshot_20240411_200316_Brave](https://github.com/Citi/gradle-helm-plugin/assets/60825512/477dd56e-b03e-4318-a829-4c8b506dcbcf)

**Comment by magner669** [comment]
Note @JamieSlome

**Comment by magner669** [comment]
See https://github.com/Citi/gradle-helm-plugin/blob/master/.github/workflows/dependency-review.yml#L8

**Comment by JamieSlome** [comment]
@magner669 - the GitHub Action will still work as intended, it just means that the bot will not automatically comment on the pull request but rather provide the feedback in the GitHub Actions terminal only.

**Comment by JamieSlome** [comment]
@magner669 - perhaps adjust the workflow to use the exact YAML:

https://github.com/finos/git-proxy/blob/main/.github/workflows/dependency-review.yml#L2-L6
