### ISSUE TITLE
[Discussion] Embed helm executable

### ISSUE THREAD

**Issue by bademux** [Citi/gradle-helm-plugin#44]
Hi,
How about discussing embedding helm binary instead of downloading\using preinstalled.

Pros:
- No compatibility issues: plugin is tested with known binary.
- Just works with no hassle. No need to worry about delivering helm binary to runtime enc like CI

Cons:
- Embedding helm binary for each JVM supported platform requires a work.
- Plugin API that allows to use external binary have to be preserved.

Thanks.

**Comment by magner669** [comment]
We are aiming for automated update of dependencies to cope with volnerabilities. How would this dependency be updated  automatically?

**Comment by bademux** [comment]
@magner669 the same as for any dependencies in the plugin. What if kotlin will have an issue?
We can employ github trigger if needed.

**Comment by magner669** [comment]
Would we include all the binaries in the  release or would we have a different release for each OS?


See also [tcnactive](https://netty.io/wiki/forked-tomcat-native.html)

**Comment by bademux** [comment]
Imho, we have to ge as generic as possible by packing all arch specific binaries to the jar

example https://github.com/hyperxpro/Brotli4j/blob/main/brotli4j/src/main/java/com/aayushatharva/brotli4j/Brotli4jLoader.java#L118

**Comment by bademux** [comment]
I see algorithm like that:

```groovy
 int helmVersion = parseVersion(`helm --version`) 
 try {
   if (parseMajor(helmVersion) <= EMBEDDED_HELM_VERSION.major){ // assume helm is backward compatible for major
     return getBinary("helm")
   }
} catch(Exception ignore) {
}
return unpackAndGetPlatformSpecificEmbeded()
```

**Comment by magner669** [comment]
Why does this have to be a feature of this plugin?

I think instead we can have another plugin which contains helm , as you say, and configures the helm executable path in this plugin.

**Comment by bademux** [comment]
perfectly suits,
 helm binaries can be embeded into a jar along with tiny Helm Java API layer\loader. 
 gradle-helm-plugin can depend on that lib.
 and both have to depend on java API provided by the lib and consumed by the plugin.
 
 If you mean "to distribute helm binary inside jar", than I believe it is misuse of maven versioning system.
 We loose version control.
 The second pitfall is that we still have to relay on download system provided by plugin; 
 btw it is hard broken right now: I have some problems with class location 
 and broken for multi project in general - plugin have to be applied to the root project to overcome multiple download processes.
 
 To summup:
- Creating working delivery system is not that simple as it might look, it is better to relay on maven\ivy\...
- It will be great to have pinned recommended versions to the plugin
- Packaging binaries into the jar is not perfect but it works in most cases (well, docker users have to mount tmp or unpack jar).

**Comment by imanushin** [comment]
> btw it is hard broken right now: I have some problems with class location

I think this is important. Do you have any advice how it can be reproduced?

> and broken for multi project in general - plugin have to be applied to the root project to overcome multiple download processes.

Yes, that could be fixed. Good point.

> The second pitfall is that we still have to relay on download system provided by plugin;

If we use an [option with jar above](https://github.com/Citi/gradle-helm-plugin/issues/44#issuecomment-2065423068), we will be able to use Gradle for this task.

E.g. Gradle can download jar from a maven repository (let's assume we provide an option for user to apply credentials and other settings). And obviously plugin can unpack that jar. Moreover, Gradle will even cache downloaded jar and our task will work with that cache.

That could be a good solution: plugin will download similar amount of bytes, Gradle will merge these downloads and we won't have any problem with custom downloads mentioned above.

**Comment by magner669** [comment]
I didint mean any of these options. 

Please be aware that gradle helm plugin has a simple API to set the helm executable path.

Someone can create a different Gradle plugin, include helm executable in it. When that plugin is enabled,  it can configure the helm executable path in this plugin.

**Comment by bademux** [comment]
Thanks,
I think issue can be closed, please reopen if needed
